### ISSUE TITLE
Implement Scan/Verify as generic procedures

### ISSUE THREAD

**Issue by czgdp1807** [lfortran/lfortran#1067]
https://github.com/lfortran/lfortran/pull/792#discussion_r988224412
https://github.com/lfortran/lfortran/pull/1037

**Comment by certik** [comment]
Both of these I think should be implemented in the surface level language runtime library (`src/runtime`, no changes to ASR), because neither our ASR optimizer nor the LLVM (or any other) backend needs to have any special knowledge of these. 

If we later decide to add some more advanced string optimizations, then we can reevaluate.
