### ISSUE TITLE
SciPy's specfun.f

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1378]
There is only one issue:
```console
$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface ./scipy/special/specfun/specfun.f
semantic error: Arguments do not match for any generic procedure, dimag
     --> ./scipy/special/specfun/specfun.f:11559:13
      |
11559 |         IF (DIMAG(Z).EQ.0.0D0.OR.XC.LT.1.0D0) LS=1
      |             ^^^^^^^^ 
```
Otherwise it compiles to ASR. LLVM then has this issue:
```console
$ lfortran --show-llvm --fixed-form --implicit-typing --implicit-interface ./scipy/special/specfun/specfun.f
code generation error: ComplexConstructor with runtime arguments not implemented yet.
```

**Comment by Pranavchiku** [comment]
Minimal example that reproduces error
```fortran

        FUNCTION DNAN()
        DOUBLE PRECISION DNAN
        DNAN = 0.0D0
        END

        SUBROUTINE CLQMN()
        IMPLICIT COMPLEX*16 (C,Z)

        IF (DIMAG(Z).EQ.0.0D00) LS=1

        END
```

**Comment by Pranavchiku** [comment]
I guess this is some problem with handling of `implicit typing` as below given code generates ASR
```fortran
SUBROUTINE CLQMN()
	IMPLICIT COMPLEX*16 (k)

	IF (DIMAG(k) == 0.0D00) LS=1
END
```

**Comment by Pranavchiku** [comment]
This is happening because we are handling `implicit_dictionary` and `implicit_mapping` in `resolve_variable` in a wrong way. What we are currently doing is checking if implicit_dicitionary is empty, yes then use implicit_mapping and hash to get appropriate implicit_dicitionary ( for a particular subroutine/function ), now if a new variable comes from another subroutine / function, it will not find implicit_dictionary empty and hence assigns wrong type.

**Comment by certik** [comment]
I can confirm that this now works:
```console
$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface ./scipy/special/specfun/specfun.f
```
Thanks @Pranavchiku for fixing it!
