### ISSUE TITLE
Unescaping strings in LPython and LFortran

### ISSUE THREAD

**Issue by czgdp1807** [lfortran/lfortran#1682]
https://github.com/lfortran/lfortran/blob/219b1451018163933773412b336cdd6503c14996/src/lfortran/parser/semantics.h#L796

Since LPython keeps strings unescaped in AST/R, I think we need to unescape strings in LFortran Frontend. Also, I think the line continuation character in Fortran is `&` (in Python it was `\`), so we should probably move the `unescape_string()` to respective frontends and update it to handle respective line continuation characters.

I am unsure if we should do the above change in this sync PR.

_Originally posted by @Shaikh-Ubaid in https://github.com/lfortran/lfortran/pull/1681#discussion_r1200917019_

**Comment by certik** [comment]
Escaping unescaping is frontend specific.

**Comment by Shaikh-Ubaid** [comment]
It seems `gfortran` treats escape sequences as regular characters by default. Also, it seems `gfortran` provides a flag `-fbackslash` to use C-style backslashing (https://stackoverflow.com/a/64494516/11474769).
```bash
$ cat examples/expr2.f90 
program expr2

print *, "hi1\nhi2\nhi3"

end program
$ gfortran examples/expr2.f90
$ ./a.out 
 hi1\nhi2\nhi3
$ gfortran -fbackslash examples/expr2.f90
$ ./a.out 
 hi1
hi2
hi3
```

How should we handle escape sequences in LFortran? Do we need to support the flag `-fbackslash`?

**Comment by certik** [comment]
I think Fortran strings do not use backslashes to escape, so I would not support it. If there is a request, we can think about it.

But I would unescape all strings in the parse and store them in AST unescaped, and definitely in ASR unescaped.

**Comment by Shaikh-Ubaid** [comment]
>But I would unescape all strings in the parser and store them in AST unescaped, and definitely in ASR unescaped.

doubt: Since escape sequences are treated as regular characters in `fortran`, which sequences/characters do we need to unescape in the parser? Please clarify.

**Comment by certik** [comment]
Basic design idea:

* Create `str_escape_fortran` and `str_unescape_fortran` and `str_escape_python` and `str_unescape_python`. If Python/C escaping is identical, then let's just use one function for both, otherwise also create `str_escape_c`.
* Then let's test these functions thoroughly using "ctest"
* In the LFortran tokenizer when a string gets tokenized, call `str_unescape_fortran` on it. The Fortran escape/unescape functions accept `"` or `'` to know how the string is quoted.
* In LPython tokenizer the string is unescaped using `str_unescape_python`
* Then in backends and printing you escape strings in whatever the backend uses, so C backend will use `str_escape_python` (or C), the (future) Fortran backend will use `str_escape_fortran`.

**Comment by Shaikh-Ubaid** [comment]
https://github.com/lfortran/lfortran/blob/838c5cfeb8ff9d93342976e6d4492b25011b2d44/src/libasr/asdl_cpp.py#L1662-L1671

In the above place, we need to escape the string when printing. This seems to conflict with working of LPython.

**Comment by certik** [comment]
For the Clojure like printing, I would escape it with what Clojure uses. It looks like Clojure does C style escaping, or very similar, so for now I would call `str_escape_c`.
