### ISSUE TITLE
[SciPy]: ASRUtils::check_equal_type(arg_type, orig_arg_type)

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1926]
```fortran
        subroutine idzp_svd(w)
        real*8 eps
        complex*16 w(*)
        call idz_realcomp(ls,w(isi))
        return
        end

        subroutine idz_realcomp(n,a)
        integer n
        real*8 a(n)
        return
        end
```

> GFortran

```console
% gfortran /Users/pgoswami/repos/scipy/scipy/linalg/src/id_dist/src/idz_svd.f
/Users/pgoswami/repos/scipy/scipy/linalg/src/id_dist/src/idz_svd.f:4:72:

    4 |         call idz_realcomp(ls,w(isi))
      |                                                                        1
Error: Type mismatch in argument 'a' at (1); passed COMPLEX(8) to REAL(8)
```

> LFortran

```console
% lfortran /Users/pgoswami/repos/scipy/scipy/linalg/src/id_dist/src/idz_svd.f --implicit-typing --implicit-interface --fixed-form --show-asr
LCOMPILERS_ASSERT failed: /Users/pgoswami/Desktop/lfortran/src/libasr/asr_utils.h
function Call_t_body(), line number 3857 at 
ASRUtils::check_equal_type(arg_type, orig_arg_type)
ERROR MESSAGE:
ASRUtils::check_equal_type(c64, r64[:])
zsh: abort      lfortran /Users/pgoswami/repos/scipy/scipy/linalg/src/id_dist/src/idz_svd.f  
```

**Comment by certik** [comment]
Ok, so in GFortran one has to use the [-fallow-argument-mismatch](https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html#index-fallow-argument-mismatch) option, citing:

> Some code contains calls to external procedures with mismatches between the calls and the procedure definition, or with mismatches between different calls. Such code is non-conforming, and will usually be flagged with an error. This options degrades the error to a warning, which can only be disabled by disabling all warnings via `-w`. Only a single occurrence per argument is flagged by this warning. `-fallow-argument-mismatch` is implied by `-std=legacy`.

> Using this option is *strongly* discouraged. It is possible to provide standard-conforming code which allows different types of arguments by using an explicit interface and `TYPE(*)`.

To fix this, let's implement an `--allow-argument-mismatch` option, and fix it by putting an implicit interface with `type(*)` in there to make it work. For example the following code:
```fortran
subroutine f()
call g(5)
call g(5.5)
end subroutine
```
which fails with gfortran, but works with `-fallow-argument-mismatch`, will also fail with LFortran, but work with `--allow-argument-mismatch` by LFortran creating the following ASR:
```fortran
subroutine f()
interface
    subroutine g(x)
    type(*) :: x
    end subroutine
end interface
call g(5)
call g(5.5)
end subroutine
```
This compiles with GFortran without any special options.

**Comment by certik** [comment]
However, the `type(*)` is weird, since we like things to be explicit in ASR. So why not something like this for the above code:
```fortran
        subroutine idz_realcomp(n,a)
        integer n
        real*8 a(n)
        return
        end

        subroutine idzp_svd(w)
        real*8 eps
        complex*16 w(*)
        interface
            subroutine idz_realcomp(n,a)
            integer n
            complex*16 a(n)
            end subroutine
        end interface
        call idz_realcomp(ls,w(isi))
        return
        end
```

I think that might be good enough for SciPy. I would use `type(*)` only if there is no other way to do this.

Overall I would not invest too much into this feature, as long as it compiles scipy I think it's good enough. If later there is some important code that needs an improvement to this, we can do that.

Btw, an alternative is to simply fix the SciPy code, which we can also consider. The code above is non-conforming (illegal / incorrect), so we can just support it on a best effort basis.

I would say: if we are going to implement this option (I would), let's implement it properly. To do that, let's not use `type(*)` and let's not use an incorrect interface. Rather, let's use the correct function interface (or an existing function), and let's cast it using a pointer. We either already allow it in ASR, and if not, let's allow it, as I think this will come handy in other situations as well.

So the code above would become:
```fortran
        subroutine idz_realcomp(n,a)
        integer n
        real*8 a(n)
        return
        end

        subroutine idzp_svd(w)
        real*8 eps
        complex*16 w(*)
        real(8), pointer :: w_cast(:)
        w_cast => real(w(isi), 8)
        call idz_realcomp(ls,w_cast)
        return
        end
```

The part `w_cast => real(w(isi), 8)` might not be allowed in Fortran, but we just do it in ASR. One can probably achieve something like this in Fortran also via `bind(c)` and some `c_ptr` casts. Let's investigate this in detail how to do this. I think Fortran already allows such casts, as does C and C++. You should not in general do that, but the language allows it, and if you do it, explicitly, then you know what you are doing and things can segfault. And so LFortran should implicitly use this feature as well. The ASR will always be well formed, and so it can be properly compiled. Down the road the pointer trick I think we can optimize out at the ASR level and/or LLVM level, so there wouldn't even be a performance hit.

Conclusion: I think ASR should always be strongly typed, and we should not use `type(*)`. We do need to sometimes cast types to each other, so we need to allow that. The existing Cast changes the bit pattern, but I think the existing BitCast node doesn't. We can't just BitCast an Out or InOut argument (only In argument), but we can use the pointer trick above to make it work.

**Comment by certik** [comment]
Here is how to do it via `c_ptr`, it compiles with gfortran:
```fortran
        subroutine idz_realcomp(n,a)
        integer n
        real*8 a(n)
        return
        end

        subroutine idzp_svd(w)
        use iso_c_binding, only: c_f_pointer, c_loc
        real*8 eps
        complex*16, target :: w(*)
        integer :: ls, isi
        real(8), pointer :: w_cast(:)
        call c_f_pointer(c_loc(w(isi)), w_cast, [10000])
        call idz_realcomp(ls,w_cast)
        return
        end
```

**Comment by Pranavchiku** [comment]
Okay, this seems interesting. I will do multiple PRs to implement this. Will start with adding test and proceed further.

**Comment by certik** [comment]
Perfect. If it turns out to be too complicated, you can work on some other issues. But I think at least the first step of C casting test (regular modern Fortran) would be useful, it's something we have to support eventually anyway.

**Comment by Pranavchiku** [comment]
TODO:

- [ ] Add test for `c_ptr` (https://github.com/lfortran/lfortran/pull/1933)
- [ ] Implement `--allow-argument-mismatch` or say `--implicit-argument-casting`

**Comment by Pranavchiku** [comment]
For the implementation part: We are going to perform implicit casting when we have a subroutine or function call with mismatched arguments, right?

**Comment by certik** [comment]
Yes, and only if the option is present.

**Comment by Pranavchiku** [comment]
I have implementation for this ready, I will open PR by tomorrow morning.

**Comment by certik** [comment]
Perfect!
