### ISSUE TITLE
`a = [a, b]` array idiom does not work

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2026]
It must automatically reallocate the LHS. This is effectively appending to a list, just really slow.

Low priority.

**Comment by certik** [comment]
1. Create `--realloc-lhs` option, off by default
2. without the option, `a = b` does not realloc, with the option it does
3. in ASR, `a = b` does NOT realloc ever
4. the frontend transforms `a = b` to either just `a = b` in ASR (no `--realloc-lhs`) or `realloc(a, size(b)); a = b` (`--realloc-lhs` supplied).
5. in Debug mode, in ASR `a = b` is checked that the sizes conform, otherwise a nice error message happens
6. in Release mode in ASR `a = b` is not checked
7. the realloc also internally checks if `a` already has the right size, if so, do nothing

**Comment by czgdp1807** [comment]
I think we are compelled to use temporary variables, because cases like the following won't work with `realloc`,

```fortran
a = [b, a]
```

If you do realloc then first `b` gets written because of which `a` gets modified. So, now in the remaining positions of `a`, the values of `b` are written (because `a` was when `b` was written to `a`). I can't think of any robust solution other than using temporaries. @ceritk Please let me know if you agree, I will proceed accordingly then.

**Comment by certik** [comment]
Yes, we need a temporary variable here. We would not need it for `a = [a, b]`, but we can just add an optimization pass that will remove the temporary variable in that case and just "appends" `b` to it.
