### ISSUE TITLE
"output = input2(n_seq+1:)" fails when output is an argument

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2054]
Workaround:
```diff
--- a/gpt2.f90
+++ b/gpt2.f90
@@ -294,7 +294,9 @@ do i = 1, n_tokens_to_generate
     end if
     deallocate(logits)
 end do
-output = input2(n_seq+1:)
+do i = 1, n_tokens_to_generate
+    output(i) = input2(n_seq+i)
+end do
 end subroutine
 
 end module
```

**Comment by Smit-create** [comment]
The bug is again related to this: https://github.com/lfortran/lfortran/issues/2044#issuecomment-1647399494

See for example:
```fortran
program name
    implicit none
    integer :: x(4)
    integer :: y(2)
    x = [1,2,3,4]
    call sub(x, y)

    print *, "main prog: ", y(1), y(2), y(3), y(4), y(5), y(6)
contains
    subroutine sub(x,y)
        integer, intent(in) :: x(:)
        integer, intent(out) :: y(:)
        y = x(2:3)
        print *, "x slice: ", x(2:3)
        print *, y(1), y(2), y(3), y(4), y(5), y(6)
    end subroutine sub
end program name
```

The output is:
```
% lfortran a.f90
x slice:  2 3 
44007680 1 1 2 3 4
main prog:  44007680 1 1 2 3 4
```

So as I mentioned in the comment linked above, `ArrayItem` is lowered using `i-LBound`. Since in `ArraySection`, we change the `LBound` and `UBound` of the array, `ArrayItem` will fail. Now in the above example, you can see that y(3), ..., y(6) is the actual array x, where as y(1), and y(2) are some random numbers because while doing `y = x(2:3)`, `LBound` is changed to `2`, and so `y(i-2) = x(i)`.

**Comment by czgdp1807** [comment]
This is because of a different bug. I will fix it once https://github.com/lfortran/lfortran/pull/2076 is merged.

**Comment by czgdp1807** [comment]
It was already fixed in https://github.com/lfortran/lfortran/pull/2070. Just add a test for it in the same PR.
