### ISSUE TITLE
Add soname to shared runtime library

### ISSUE THREAD

**Issue by bkmgit** [lfortran/lfortran#2096]
It would be helpful to add a soname to the shared runtime library to enable distinguishing between different releases and for packaging in linux distributions.

**Comment by certik** [comment]
@bkmgit I had to revert your PR in https://github.com/lfortran/lfortran/pull/2123 as it broke a test that we added in the meantime. Here is the failure: https://github.com/lfortran/lfortran/actions/runs/5801462841/job/15725785602
```
_ ERROR collecting build-install/lib/python3.10/site-packages/scipy/special/tests/test_basic.py _
ImportError while importing test module '/home/runner/work/lfortran/lfortran/scipy/build-install/lib/python3.10/site-packages/scipy/special/tests/test_basic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/runner/micromamba/envs/scipy-dev/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/special/__init__.py:772: in <module>
    from . import _ufuncs
E   ImportError: liblfortran_runtime.so.0: cannot open shared object file: No such file or directory
_ ERROR collecting build-install/lib/python3.10/site-packages/scipy/special/tests/test_bdtr.py _
```

It might be easy to fix, but there is some issue with how the runtime library handling has changed as a result of #2115.


There is also another potential issue reported in: https://lfortran.zulipchat.com/#narrow/stream/197339-general/topic/Integration.20Tests.20Error/near/383281399:

> I'm getting these 2 files generated. Can you please advise what's going wrong?
src/runtime/liblfortran_runtime.so.0
src/runtime/liblfortran_runtime.so.0.19.0-898-g3304de573

I don't know if this is the expected behavior or not, or if it causes some issues.
