### ISSUE TITLE
simple generics: lapack wrapper

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2267]
@dacarnazzola has the full example but roughly:
```
interface gemm
    interface sgemm ! exact Lapack interface
    end interface

    SUBROUTINE DGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    import :: dp
    DOUBLE PRECISION ALPHA,BETA
    INTEGER K,LDA,LDB,LDC,M,N
    CHARACTER TRANSA,TRANSB
    REAL(dp) A(LDA,*),B(LDB,*),C(LDC,*)
    END SUBROUTINE

    SUBROUTINE CGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    COMPLEX ALPHA,BETA
    INTEGER K,LDA,LDB,LDC,M,N
    CHARACTER TRANSA,TRANSB
    COMPLEX A(LDA,*),B(LDB,*),C(LDC,*)
    END SUBROUTINE

    interface zgemm ! exact Lapack interface
    end interface
end interface

function my_matmul{T, gemm}(A, B) result(C)
type(T), intent(in) :: A(:,:), B(:,:)
type(T) :: C(:,:)
call gemm(..., A, .., B, .., C)
end function


! gemm is looked up in the local scope, and "gemm" above is matched
! T is inferred from the type of A/B
C = my_matmul(A, B)
```

**Comment by dacarnazzola** [comment]
A generic wrapper to `LAPACK`'s `sgemm`, `dgemm`, `cgemm`, and `zgemm` can be represented the following way:
```fortran
module library_m
implicit none

    public :: external_matmul, gemm

    interface gemm
        subroutine sgemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            real, intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            real, intent(out) :: c(ldc,*)
        end subroutine sgemm
        subroutine dgemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            double precision, intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            double precision, intent(out) :: c(ldc,*)
        end subroutine dgemm
        subroutine cgemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            complex, intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            complex, intent(out) :: c(ldc,*)
        end subroutine cgemm
        subroutine zgemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            double complex, intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            double complex, intent(out) :: c(ldc,*)
        end subroutine zgemm
    end interface gemm

    requirement gemm_r(T, gemm)
        subroutine gemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            type(T), intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            type(T), intent(out) :: c(ldc,*)
        end subroutine gemm
    end requirement gemm_r

    requirement cast_r(T, U, cast)
        type, deferred :: T, U
        pure elemental function cast(arg) result(res)
            type(T), intent(in) :: arg
            type(U) :: res
        end function cast
    end requirement cast_r

    contains

        subroutine external_matmul{T, gemm_in, cast_to_T}(a, b, c)
            requires :: gemm_r(T=T, gemm=gemm_in), &
                        cast_r(T=real, U=T, cast=cast_to_T)
            type(T), intent(in) :: a(:,:), b(:,:)
            type(T), intent(out) :: c(:,:)
            integer :: m, n, k
            m = size(a, dim=1)
            n = size(b, dim=2)
            k = size(a, dim=1)
            call gemm('n', 'n', m, n, k, cast(1.0), a, m, b, k, cast(0.0), c, m)
        end subroutine external_matmul

end module library_m
```

A normal interface block aggregates `sgemm`, `dgemm`, `cgemm`, and `dgemm` for the intrinsic types `real`, `double precision`, `complex`, and `double complex`. Then, a single generic subroutine `external_matmul` can call `gemm`, specified in the requirement `gemm_r`. The `gemm` interface from `gemm_r` matches the module's `interface gemm`, and will properly match the intrinsic types with their correct calls. We still need the `cast_to_T` concept, which in this case will cast the `real` constants `1.0` to alpha and `0.0` to beta.

Note that the `interface gemm` is made public, this way callers of `external_matmul` can bring it into scope for reuse with the covered intrinsic types.

An example program using this generic subroutine could look like:
```fortran
program main
use, non_intrinsic :: library_m, only: external_matmul, gemm
implicit none

    real :: asp(2,2), bsp(2,2), csp(2,2)
    double precision :: adp(2,2), bdp(2,2), cdp(2,2)

    call random_number(asp)
    call random_number(bsp)

    call external_matmul(asp, bsp, csp)
    write(*,*) 'sgemm: ',csp !! external_matmul::gemm finds imported (interface gemm)::sgemm

    call random_number(adp)
    call random_number(bdp)

    call external_matmul(adp, bdp, cdp)
    write(*,*) 'dgemm: ',cdp !! external_matmul::gemm finds imported (interface gemm)::dgemm

end program main
```

In this case, the subroutine `external_matmul` was written rather restrictively, expecting matrix inputs, assuming no transposes are ever desired, as well as `alpha=1.0` and `beta=0.0`. This is not immediately useful for user-written derived-types, unless they also would represent single elements of a larger matrix. However, with the requirement `gemm_r` available, it is conceivable that a `derived_type_gemm` routine could be written, and it would be callable with the same `external_matmul` subroutine if so desired.

The `external_matmul` routine could also be rewritten to expose the entire interface, allowing more control to callers, but at that point the "simplified wrapper" objective would be moving further and further away.

**Comment by dacarnazzola** [comment]
I have updated this example to correct the semantics described in comments of `program main` as well as separated `interface gemm` into its own module for clarity. Now, it is clear that "functions to satisfy requirements" must come from the call site.

**Comment by dacarnazzola** [comment]
A few points:
1. parameter list `{}` containing type parameters and function parameters - got it
2. argument list `()` containing dummy arguments - got it
3. make `external_matmul` a function rather than subroutine - got it

However, before I convert it over, your post @certik has highlighted some questions I have...
* It was my understanding that, in the parameter list of a generic procedure declaration, type parameters and function parameters could have any names the author wanted.
* Next, the requirements themselves have `arguments`, which may be type arguments or function arguments I suppose.
* Syntax that looks like `requires :: gemm_r(T=input_type_parameter, gmm=input_function_parameter)` indicates that our generic code's type parameter `input_type_parameter` is meant to match the `requirement gemm_r`'s `type argument T`, and function parameter `input_function_parameter` matches the function argument `gemm` from `gemm_r`.
* I wrote these procedures using the procedure name from the `requirement`, because I thought that's what became available when a "requirement was satisfied."
* It seemed to me that using the function parameter names would make reuse more difficult, because then how would operators work? When a requirement is defining a function to provide an operator, we want the operator (say `+`) to be available for use in the generic procedure code (`arg1 + arg2`), not having to call `add(arg1, arg2)`.
* If we use the function parameter name, then does that mean to have operators be usable, they need to be defined externally (in the calling scope) already? Meaning, I could not write some `function my_addition(arg1, arg2) result(res)` and supply it to some generic procedure looking for that signature to use as `operator(+)`? Would I have to overload `operator(+)` in the calling scope to have that behavior be legal?

**Comment by certik** [comment]
It's totally up to us how we design it. We can design it that it will be the name from the requirement, not the parameter list that will be used. That seems counter intuitive to me, but we can design it that way. Either way, this is minor. I discussed with @ansharlubis, we can start implementing this, step by step. We can iterate on these details as we go.

**Comment by dacarnazzola** [comment]
I'll adjust the example to be a function and use the function parameter names. That lets `requirements` be written with clear, potentially longer than one would like to write out many times, function argument names, and "consumers" (generic code) be written with function parameter names that make sense locally.

Of course the intention is to iterate, and I think part of that process is trying to check that the rules/semantics described are consistent as we go.

**Comment by certik** [comment]
Why cannot `gemm_in` just be called `gemm`?

**Comment by dacarnazzola** [comment]
I wanted the example to be very clear that there are multiple _**independent**_ parts that work together:
* `requirement gemm_r` takes a function argument `gemm`, which must conform to the `subroutine gemm` signature within
* the generic function `external_matmul` takes a function parameter `gemm_in`, which will be used to satisfy the requirement `gemm_r`'s `gemm` subroutine definition
* completely separately, the `module external_interfaces_m` provides `interface gemm`, which allows matching `call gemm` to one of `sgemm`, `dgemm`, `cgemm`, or `zgemm` - I provided no definition for these so for these files to compile, some linking some library with those subroutines defined would be a good way to actually make them usable
* the `program main` imports `gemm` from `external_interfaces_m`, which is unrelated to the `requirement gemm_r`, which just so happens to have a function argument with matching signature. But, with the `interface gemm` in scope for `program main`, the linked library subroutines `sgemm`, `dgemm`, `cgemm`, and `zgemm` are available and the compiler should be able to match the correct one based on the type supplied to `external_matmul`, in order to match the function parameter `gemm_in`

It could be my non-CS background, but if everything was just `gemm`, at least I would find it a bit more confusing _**exactly which**_ procedure/signature was being used where and how the pieces were meant to flow together. Honestly, I considered renaming the `requirement gemm_r`'s function argument and subroutine definition to use a different name, like `required_gemm`.

**Comment by certik** [comment]
Sure, we can have this as an example. In that case I think this line
```
use, non_intrinsic :: external_interfaces_m, only: gemm
```
must be changed to
```
use, non_intrinsic :: external_interfaces_m, only: gemm_in => gemm
```

**Comment by dacarnazzola** [comment]
The example has been updated to reflect your changes.

I guess this means we are saying that the calling scope of a generic procedure needs to provide a procedure that matches the function parameter's **name** as well as **signature**? I did not realize that before, and thought the calling scope only had to provide a procedure that matched the _signature_. Perhaps that would normally be the case, but for the first iteration of compiler inference we will say the caller needs to have _name_ and _signature_ matching, in scope, in order for the compiler to "find it" implicitly?

I think there would be many cases where there is only one matching signature regardless of name, but maybe it would be more difficult to come up with meaningful error messages in the event that multiple matching signatures were in scope without matching names.

**Comment by certik** [comment]
Let's write down the instantiation in full. The short syntax:
```
    csp = external_matmul(asp, bsp)
```
is a syntactic sugar for:
```
    csp = external_matmul{T=real,gemm_in=gemm_in,cast_to_T=real}(asp, bsp)
```

**Comment by certik** [comment]
Here is a first full example that we should try to get working.
```fortran
module external_interfaces_m
implicit none
private

    public :: gemm

    interface gemm
        subroutine sgemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            real, intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            real, intent(out) :: c(ldc,*)
        end subroutine sgemm
        subroutine dgemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            double precision, intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            double precision, intent(out) :: c(ldc,*)
        end subroutine dgemm
        subroutine cgemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            complex, intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            complex, intent(out) :: c(ldc,*)
        end subroutine cgemm
        subroutine zgemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            double complex, intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            double complex, intent(out) :: c(ldc,*)
        end subroutine zgemm
    end interface gemm

end module external_interfaces_m



module library_m
implicit none
private

    public :: external_matmul

    requirement gemm_r(T, gemm)
        type, deferred :: T
        subroutine gemm(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
            character, intent(in) :: transa, transb
            integer, intent(in) :: m, n, k, lda, ldb, ldc
            type(T), intent(in) :: alpha, a(lda,*), b(ldb,*), beta
            type(T), intent(out) :: c(ldc,*)
        end subroutine gemm
    end requirement gemm_r

    requirement cast_r(T, U, cast)
        type, deferred :: T, U
        pure elemental function cast(arg) result(res)
            type(T), intent(in) :: arg
            type(U) :: res
        end function cast
    end requirement cast_r

    contains

        function external_matmul{T, gemm, cast_to_T}(a, b) result(c)
            require :: gemm_r(T=T, gemm=gemm), &
                        cast_r(T=real, U=T, cast=cast_to_T)
            type(T), intent(in) :: a(:,:), b(:,:)
            type(T) :: c(size(a,1), size(b,2))
            integer :: m, n, k
            m = size(a, dim=1)
            n = size(b, dim=2)
            k = size(a, dim=1)
            call gemm('n', 'n', m, n, k, cast_to_T(1.0), a, m, b, k, cast_to_T(0.0), c, m)
        end function external_matmul

end module library_m

program main
use, non_intrinsic :: library_m, only: external_matmul
use, non_intrinsic :: external_interfaces_m, only: gemm
implicit none

    real :: asp(2,2), bsp(2,2), csp(2,2)
    double precision :: adp(2,2), bdp(2,2), cdp(2,2)

    call random_number(asp)
    call random_number(bsp)

    ! csp = external_matmul(asp, bsp)
    csp = external_matmul{T=real,gemm=sgemm,cast_to_T=real}(asp, bsp)
    write(*,*) 'sgemm: ',csp 

    call random_number(adp)
    call random_number(bdp)

    ! cdp = external_matmul(adp, bdp)
    csp = external_matmul{T=real(dp),gemm=dgemm,cast_to_T=dble}(asp, bsp)
    write(*,*) 'dgemm: ',cdp

end program main

```
