### ISSUE TITLE
Divergence in the output of `selected_int_kind()` for LFortran and GFortran

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2551]
Reference: https://github.com/lfortran/lfortran/issues/602
`selected_real_kind()` and `selected_int_kind()` are implemented now but `selected_int_kind` gives divergence with GFortran.
```fortran
program main
    print*, selected_real_kind(2)
    print*, selected_int_kind(4)
end 
```
```console
$ gfortran a.f90 && ./a.out 
           4
           2
$ lfortran a.f90
4
4
```

**Comment by certik** [comment]
I think `selected_int_kind(R)` uses the condition `-10^R < n < 10^R` to find such integer kind to fit all "n" in it. So for R=4, we have `-10,000 < n < 10,000`, so kind=1 is too small, but kind=2 is good enough, since 16bit integer can fit all those `n`. The standard says "If more than one kind type parameter meets the criterion, the value returned is the one with the smallest decimal exponent range". So LFortran returns the correct kind. GFortran must not support kind=2 for integers, so its smallest kind is 4.

I think both outputs are correct.

Is this causing some issue in some code?

**Comment by kargl** [comment]
certik, I think you need to re-read the results.  gfortran returns the correct result.  lfortran, if it supports a 16-bit signed integer, is returning the incorrect result.

**Comment by certik** [comment]
@kargl you are right! I misread it --- indeed gfortran is correct and since we do support 16bit signed integers internally (I think even in LFortran), then LFortran is indeed incorrect and must return 2 as well. Thanks for spotting it! Something felt off here, since so far we managed to match GFortran exactly in almost every case (sometimes with some extra compiler options), so I am happy we can match it exactly here as well.

@HarshitaKalani LFortran must return 2 like GFortran.
