### ISSUE TITLE
ASR pass to promote allocatable arrays to non-allocatable arrays

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2656]
The pass should be able to transform the following:
```fortran
integer, intent(in) :: n
real, allocatable :: x(:)
allocate(x(n))
```
into:
```fortran
integer, intent(in) :: n
real :: x(n)
```
And many other similar cases.

**Comment by czgdp1807** [comment]
I don't think we need a full pass for this especially while creating allocatables. In fact, while create an allocatable you can check whether you need one, if not then just don't create an allocatable. And if some user created variable is an allocatable then I would keep it as it is.

**Comment by certik** [comment]
Yes, this pass is low priority, because we don't need it for temporaries, and users can always change it themselves.

However it is not clear that we 100% won't need this pass, because you can imagine a function returning an allocatable that gets inlined, and then the allocatable can be promoted to non-allocatable. The user can't do it unless he changes the function itself. On the other hand, one is encouraged to only use allocatable if the size cannot be inferred from function parameters, however I do not know if this can be done in all cases.

Conclusion: low priority, but we might end up needing this pass.

**Comment by czgdp1807** [comment]
I think we need it. I just tried avoiding allocatables and I think the logic will be complex. A pass would be easy on us and would deal with all allocatables at once. However we can keep it limited only to local variables in a scope because only the leak memory and temporaries are local variables anyways. And changing the type of a local variable is safe I think.

**Comment by czgdp1807** [comment]
But still I would keep it low priority.
