### ISSUE TITLE
BUG: `gamma` had to be renamed to `mgamma`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3019]
For `gamma` had to be renamed to `mgamma`, the below diff makes it work along with changing function calls to `mgamma`

```diff
diff --git a/example/specialfunctions_gamma/example_gamma.f90 b/example/specialfunctions_gamma/example_gamma.f90
index 7a1107f..ddbc694 100644
--- a/example/specialfunctions_gamma/example_gamma.f90
+++ b/example/specialfunctions_gamma/example_gamma.f90
@@ -1,6 +1,6 @@
 program example_gamma
   use stdlib_kinds, only: dp, int64
-  use stdlib_specialfunctions_gamma, only: mgamma
+  use stdlib_specialfunctions_gamma, only: mgamma => gamma
   implicit none
 
   integer :: i
```

Question: How does a compiler differentiate call to intrinsic `gamma` and `gamma` defined in module (`mgamma`)

```fortran
  print *, gamma(n)
! 87178291200

  print *, gamma(x)              ! intrinsic function call
! 1.32934034
```

cc @certik @czgdp1807

**Comment by certik** [comment]
I think the way to fix this is as follows:

1. Lookup the `gamma` symbol in the scoped symbol table. It will find the user `gamma` (if it doesn't find it, use intrinsic).
2. Check if any of the user `gamma` fits the argument list. If it does, use it.
3. If not, continue looking into the intrinsic function `gamma` versions and see if any fits the argument list. If so, use it.
4. If not, give an error message that we can't find the specific `gamma` function in scope (say `gamma("abc")`).

We already have (roughly) this design. However, the bug is that in the step 3. we override the user ExternalSymbol with the intrinsic. So that becomes a problem on the next line which should find the user function (it will not be there anymore).

To fix that, we need to keep the user ExternalSymbol intact, in scope. One way to fix it is to rename the intrinsic that we insert, to not clash with the user symbol.
