### ISSUE TITLE
semantic error: Function not found

### ISSUE THREAD

**Issue by junghans** [lfortran/lfortran#3272]
If I have two files, `hello.f` and `main.f`, with the former being:
```Fortran
	SUBROUTINE HELLO
	PRINT *, 'Hello'
	END
```
and the latter being:
```Fortran
	PROGRAM MAIN
	CALL HELLO()
	END
```

I get an error when compiling the second file into an object:
```
$ lfortran -c main.f 
semantic error: Function 'hello' not found or not implemented yet (if it is intrinsic)
 --> main.f:2:2
  |
2 |  CALL HELLO()
  |  ^^^^^^^^^^^^ 
```
while `gfortran` eats that fine.

Any suggestions?

Related to #3208

**Comment by certik** [comment]
There are several issues here. Here is how you get it working:
```console
$ lfortran -c main.f --implicit-interface --generate-object-code
$ lfortran -c hello.f --generate-object-code
$ lfortran -o hello main.o hello.o                              
$ ./hello 
Hello
```
The issues are:
* implicit function interface: not allowed by default, but you can enable with `--implicit-interface`
* You are not compiling modules into mod files, but rather lose global subroutines without an interface. For this case you need to use `--generate-object-code` to generate code in the `.o` file. By default LFortran stores all the code in `.mod`, and compiles at the very end. See also https://github.com/lfortran/lfortran/issues/2955.

**Comment by junghans** [comment]
What is the difference between `-c` and `-c --generate-object-code`? I think I am a bit confused that even without `--generate-object-code` a `.o` file gets generated.

**Comment by certik** [comment]
The generated `.o` file is empty, and we don't use it. The only reason we generate it is to satisfy cmake, it will refuse to work with lfortran otherwise. 

We have two modes of compilation. One is the traditional one that generates object files and then links everything at the end, which is currently triggered via `--generate-object-code`. And then we have a mode that we save all code into `.mod` files and then compile everything at the end, which is currently the default. See #2955.

I don't know if there is a way to support both with cmake and what the best compiler options and defaults should be.

**Comment by junghans** [comment]
I figured that one out!
