### ISSUE TITLE
Bug: `read()` gives invalid output

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4015]
This bug was caught when working on #4011.

> b.f90
```fortran
program main
    character :: c
    open(11, file="intrinsics_60_data.txt", form="formatted", access="stream", status="old")
    read(11, *) c
    print *, c
    print*, len(c)
end
```
```console
$ gfortran b.f90 && ./a.out
 H
           1
$ lfortran b.f90 --no-warnings
Hello
5
```

> intrinsics_60_data.txt
```
Hello
```

When ready with a fix, please also verify the integration test `intrinsics_60.f90`.

**Comment by gxyd** [comment]
Seems like `_lfortran_read_char` doesn't take into account the length of the passes character string to it. Probably needs another argument for it. The same issue currently happens for when the input is taken from the console:
```f90
program main
    character(len=2) :: c
    read *, c
    print *, c
    print*, len(c)
end
```

if we enter "apple" as the string from console. It will output:
```bash
apple
5
```

instead of the correct output:
```bash
ap
2
```

Same issue happens for when, padding of spaces needs to be done.

**Comment by kmr-srbh** [comment]
@gxyd thanks for the finding! This should be easy to fix I think. :+1:

**Comment by kmr-srbh** [comment]
@gxyd are you working on this? I have fix ready for this.

**Comment by gxyd** [comment]
I was going to submit a fix just now, but I'm happy to work on this together so that either of our solution can be merged. So, submit a PR for it, and I'll review that.
