### ISSUE TITLE
[Compile LAPACK] declaring arrays in subroutines

### ISSUE THREAD

**Issue by KGB99** [lfortran/lfortran#4404]
I believe I found a problem with the declaration of arrays in subroutines when the length for the array is a parameter as well.
I have the following example program derived from `blas/src/xerbla_array.f` [here](https://github.com/Reference-LAPACK/lapack):
```
      PROGRAM EXAMPLE_ERROR
            
            INTEGER A
            CHARACTER B(1)
            
            A = 1
            CALL ERROR_SUBROUTINE(B,A)

      END PROGRAM


      SUBROUTINE ERROR_SUBROUTINE(B, A)
      
            INTEGER A 
            CHARACTER B(A)
            
            B = 'X'
            PRINT *, B

            RETURN

      END
```

The output of `gfortran example.f` is `X`, whereas `lfortran --fixed-form --show-llvm example.f` is:
```
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/kerimbirgi/dev/lfortran/src/bin/lfortran.cpp", line 2478
    LCompilers::print_stack_on_segfault();
  File "/Users/kerimbirgi/dev/lfortran/src/bin/lfortran.cpp", line 2362
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/kerimbirgi/dev/lfortran/src/bin/lfortran.cpp", line 852
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/kerimbirgi/dev/lfortran/src/lfortran/fortran_evaluator.cpp", line 295
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/kerimbirgi/dev/lfortran/src/lfortran/fortran_evaluator.cpp", line 317
    diagnostics, lm.files.back().in_filename);
  File "/Users/kerimbirgi/dev/lfortran/src/lfortran/fortran_evaluator.cpp", line 363
    compiler_options, run_fn, infile);
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9973
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 5154
  File "../libasr/asr.h", line 5130
  File "../libasr/asr.h", line 5155
  File "../libasr/asr.h", line 4861
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 953
    visit_Function(*ASR::down_cast<ASR::Function_t>(item.second));
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3858
    llvm_goto_targets.clear();
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3899
    llvm::FunctionType* function_type = llvm_utils->get_function_type(x, module.get());
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/codegen/llvm_utils.cpp", line 1133
    std::vector<llvm::Type*> args = convert_args(x, module);
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/codegen/llvm_utils.cpp", line 911
    type_original = get_arg_type_from_ttype_t(arg->m_type,
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/codegen/llvm_utils.cpp", line 668
    LCOMPILERS_ASSERT(false);
AssertFailed: false
```
Both `--show-ast` and `--show-asr` produce outputs therefore I assume the error happens during the ASR to LLVM translation. Any help or guidance is appreciated.

**Comment by kmr-srbh** [comment]
Great catch, @KGB99! 

It seems this issue is present in the free-form version of the code also, so I think it is not specific to fixed-form Fortran. 

If we do `lfortran ./examples/example.f90 --dump-all-passes` and look at the generated ASR file at `pass_31_insert_deallocate.clj`, we notice that the generated ASR has `b` declared as `CharacterArraySinglePointer` with `Unspecified` intent inside the `ERROR_SUBROUTINE` subroutine.

```clojure
b:
      (Variable
            3
            b
            [a]
            Unspecified
            ()
            ()
            Default
            (Array
                  (Character 1 1 ())
                  [((IntegerConstant 1 (Integer 4))
                  (Var 3 a))]
                  CharacterArraySinglePointer
            )
            ()
            Source
            Public
            Required
            .false.
      )
```

Here is the final transformed Fortran code after applying all the ASR passes, obtained through `lfortran ./examples/example.f90 --dump-all-passes-fortran`:

```fortran
! Fortran code after applying the pass: insert_deallocate
program example_error
implicit none
integer(4) :: a
character(len=1, kind=1), dimension(1) :: b
a = 1
call error_subroutine(b, a)

contains

subroutine error_subroutine(b, a)
    integer(4) :: k
    integer(4) :: t
    integer(4) :: a
    character(len=1, kind=1), dimension(a) :: b
    t = 1 - 1
    do while (t + 1 <= a + 1 - 1)
        t = t + 1
        b(t) = "X"
    end do
    k = 1 - 1
    do while (k + 1 <= a + 1 - 1)
        k = k + 1
        print *, b(k)
    end do
    print *
    print *
    return
end subroutine error_subroutine

end program example_error
```

I think we probably need to handle the parameter `b` inside the subroutine similar to a reference parameter in C++?

Modifying `character(len=1, kind=1), dimension(a) :: b` to `character(len=1, kind=1), intent(inout), dimension(:) :: b` gives the output:
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
 X


(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
X


```

PS: The actual generated code had variables `k` and `t` named as `__1_k` and `__1_t` respectively. I have modified the names to make it work with GFortran.

**Comment by kmr-srbh** [comment]
Great catch, @KGB99! 

It seems this issue is present in the free-form version of the code also, so I think it is not specific to fixed-form Fortran. 

If we do `lfortran ./examples/example.f90 --dump-all-passes` and look at the generated ASR file at `pass_31_insert_deallocate.clj`, we notice that the generated ASR has `b` declared as `CharacterArraySinglePointer` with `Unspecified` intent inside the `ERROR_SUBROUTINE` subroutine.

```clojure
b:
      (Variable
            3
            b
            [a]
            Unspecified
            ()
            ()
            Default
            (Array
                  (Character 1 1 ())
                  [((IntegerConstant 1 (Integer 4))
                  (Var 3 a))]
                  CharacterArraySinglePointer
            )
            ()
            Source
            Public
            Required
            .false.
      )
```

Here is the final transformed Fortran code after applying all the ASR passes, obtained through `lfortran ./examples/example.f90 --dump-all-passes-fortran`:

```fortran
! Fortran code after applying the pass: insert_deallocate
program example_error
implicit none
integer(4) :: a
character(len=1, kind=1), dimension(1) :: b
a = 1
call error_subroutine(b, a)

contains

subroutine error_subroutine(b, a)
    integer(4) :: k
    integer(4) :: t
    integer(4) :: a
    character(len=1, kind=1), dimension(a) :: b
    t = 1 - 1
    do while (t + 1 <= a + 1 - 1)
        t = t + 1
        b(t) = "X"
    end do
    k = 1 - 1
    do while (k + 1 <= a + 1 - 1)
        k = k + 1
        print *, b(k)
    end do
    print *
    print *
    return
end subroutine error_subroutine

end program example_error
```

I think we probably need to handle the parameter `b` inside the subroutine similar to a reference parameter in C++?

Modifying `character(len=1, kind=1), dimension(a) :: b` to `character(len=1, kind=1), intent(inout), dimension(:) :: b` gives the output:
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
 X


(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
X


```

PS: The actual generated code had variables `k` and `t` named as `__1_k` and `__1_t` respectively. I have modified the names to make it work with GFortran.

**Comment by certik** [comment]
I think the ASR looks correct, it looks like there might be some issue in the LLVM backend that handles this case. We need to investigate.

**Comment by Pranavchiku** [comment]
Here physical cast of variable `b` is `CharacterArraySinglePointer` which is incorrect, it should be a `DescriptorArray` instead. To read more about when we use `CharacterArraySinglePointer` here is link to https://github.com/lfortran/lfortran/pull/2929#issuecomment-1845897861 it

**Comment by Pranavchiku** [comment]
The following diff gets example working, although there maybe a few integration tests that fail which needs to be figured out:

```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 72918a831..5ab42ac48 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -3433,11 +3433,12 @@ public:
             if (sym_type->m_kind == nullptr) {
                 a_len = 1; // The default len of "character :: x" is 1
             }
+            std::cout<<"in here"<<"\n";
             LCOMPILERS_ASSERT(a_len != -10)
             type = ASRUtils::TYPE(ASR::make_Character_t(al, loc, a_kind, a_len, len_expr));
             type = ASRUtils::make_Array_t_util(
                 al, loc, type, dims.p, dims.size(), abi, is_argument,
-                dims.size() > 0 ? ASR::array_physical_typeType::CharacterArraySinglePointer : ASR::array_physical_typeType::DescriptorArray,
+                dims.size() > 0 && abi == ASR::abiType::BindC ? ASR::array_physical_typeType::CharacterArraySinglePointer : ASR::array_physical_typeType::DescriptorArray,
                 dims.size() > 0 ? true : false);
             if( char_data->scope != nullptr ) {
                 char_data->type = type;
```

**Comment by Pranavchiku** [comment]
> I think we probably need to handle the parameter b inside the subroutine similar to a reference parameter in C++?

Thanks @kmr-srbh for elaborating about the issues. I didn't quite understand what does this mean, do we not pass every parameter as reference by default in fortran?

**Comment by Pranavchiku** [comment]
PR to fix this: https://github.com/lfortran/lfortran/pull/4417

**Comment by kmr-srbh** [comment]
> do we not pass every parameter as reference by default in fortran

I think we do, GFortran does the same for the above code. I had made the above suggestion because I think we are re-declaring the variable `b` as seen in the transformed code? `intent(inout)` is the closest to references in Fortran and so I suggested it. I do not know if it is the correct way to approach this, it is just a suggestion.

![image](https://github.com/lfortran/lfortran/assets/151380951/648ea233-3495-476d-aa59-89c766dd3e02)

I get the above warning in the linter, but surprisingly GFortran does not raise any warnings even with the `-Wall -Wextra` options. I request you to correct me if I am going wrong, I am still learning.

**Comment by Pranavchiku** [comment]
Your approach to debug seems correct and the first comment makes sense. 

> I had made the above suggestion because I think we are re-declaring the variable b as seen in the transformed code?
 
In Fortran every variable has a scope ( scoped language ), so `b` inside `Program` is different to `b` inside `subroutine`, you can understand it by the way we handle `SymbolTable`. Thus we are not re-declaring a variable.

I am not sure about the squiggle that you have presented in image. Rest your understanding is good, keep up the work :)

**Comment by kmr-srbh** [comment]
Thanks @Pranavchiku! I am striving to gain a good understanding of Fortran and the code-base. Your input is always appreciated!
