### ISSUE TITLE
Fail on fixed-form line with text only past col 72

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5311]
I started trying to run the FCVS_95 validation suite mentioned in issue #480, but I encountered a case not covered by my PR #5306:
```fortran
      CHARACTER CVTN01*1                                                00760402
                                                                        00770402
```
Source in the form of the second line, which consists only of text past column 72, is being misinterpreted in a variety of ways by the fixed-form parser.  I'll work on a fix.

**Comment by certik** [comment]
Thanks! We probably missed this case.

Thanks for working on the FCVS_95 suite, it's a good one to ensure F77 style code works robustly. We should have all the features mostly implemented for F77 (except common blocks #661), but you'll discover bugs like you did with `save`, there might also be some parsing bugs, since the fixed-form tokenizer has been only tested on SciPy and a few other F77 codes, but not extensively otherwise. The Bison parser is used for both fixed- and free-form, so it should be quite robust.
