### ISSUE TITLE
Syntax vs. Semantic error

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5426]
There are a set of error tests that look something like:
```f90
program kind2
implicit none

real(*) a

end program
```
which currently returns
```
semantic error: Expected initialization expression for kind
 --> tests/errors/kind2.f90:4:6
  |
4 | real(*) a
  |      ^ 
```
I'm working on tightening up the parser in places, and, according to the standard, this statement is _syntactically_ invalid, not semantically.  With rules like the standard's _kind-selector_ in place, I get a parsing error of:
```
syntax error: Token ')' is unexpected here
 --> tests/errors/kind2.f90:4:7
  |
4 | real(*) a
  |       ^ 
```
since `*` is not a valid _scalar-int-constant-expr_.  How do people feel about this sort of change?  I'm tagging @gxyd as they put in the `kind_star_of_int` test that first caught this change.

**Comment by certik** [comment]
Thanks for bringing this up.

Which error is better:
* `Expected initialization expression for kind`
* `Token ')' is unexpected here`

I would say the first one is better --- we can even further improve it, since we have access to the AST, so we can explain to the user exactly what is wrong. The second error just says that ")" is not expected there, but it doesn't tell the user why.

My opinion is still evolving on how to best design the parsing and semantics, when we started, we were trying to figure out a lot of the structure in the parser itself, but then later I realized that it is much better if the parser can just give some AST, and we take care of errors in AST->ASR even if they can be caught by the parser itself. One example of this is https://github.com/lfortran/lfortran/issues/5273 where we currently use the parser to figure out the order of statements, but it's actually easier (more maintainable, less code, better error messages) to make the parser more general and parse any order, and then check the order later.

The error messages that we can give in the parser are limited, typically we can show the location and some error like ")" is unexpected, but that's about it. The error messages we can give in AST->ASR are rich: we can highlight multiple places, we can figure out exactly what the user did, and we understand the context, so we can explain exactly what the actual problem is.

If the issue is that it prints "semantic error" we can introduce a third category for these kinds of errors that are technically syntax errors, but we catch then not during parsing, but in AST->ASR. And we can print those as "syntax errors" (or perhaps distinguish it somehow from syntax errors caught by the parser). So far I like to somehow tell the user which part of the compilation process the error comes from.

One more aspect is editor integration: for that we need error resilient parser/semantics; so being able to parse the above incorrect code into AST, we can then report an error and create some reasonable ASR out of it, which is then used for various editor tasks, like a symbol lookup. For example, let's say that the user looks up "a" later in the code, and "a" was declared incorrectly as "real(*) a". Well, if we catch this in AST->ASR, we can still choose to add "a" into the symbol table, perhaps with the default kind (4), and so symbol lookup would still work. If, on the other hand, we catch this in the parser itself, then we have to recover from the error in the parser, but this line will not be represented in AST, nor ASR, so we can't lookup the symbol.

My current view is that it seems better to make the parser as general as possible and parse anything that can be parsed into AST, and then take care of all errors in AST->ASR.

**Comment by pjh40** [comment]
I appreciate the insight, and completely agree that the current error message is more rich.  I'm not hung-up on the "semantic" vs "syntax" error label, although the latter is probably more accurate.  

This issue came up as I'm working on #5352: handling (valid) syntax like 
```f90
implicit integer(kind=4)(a)
implicit real(4+4)(q-s)
```
causes more shift/reduce errors in the parser, so I was trying to see if more specific parsing rules for _kind-selector_ would reduce the number of errors.  I don't think that it does, so I can back those changes out.

At some point though, we can't diagnose all syntax errors without essentially accepting all input as valid.  Using a modification of your example, `real(,) a` would result in the same syntax error shown in my original comment.  Does `real(*) a` "deserve" better treatment?  Maybe, if we have data that it is a common error.   But adding more ambiguity to the parser may mean a larger and slower parser, so we'll have to keep an eye on that.

**Comment by certik** [comment]
I agree. We definitely want fast parser, as unambiguous as we can get. Specifically, the current parser is unambiguous LALR(1) if you apply the following patch:
```diff
--- a/src/lfortran/parser/parser.yy
+++ b/src/lfortran/parser/parser.yy
@@ -3,9 +3,7 @@
 %define api.value.type {LCompilers::LFortran::YYSTYPE}
 %param {LCompilers::LFortran::Parser &p}
 %locations
-%glr-parser
-%expect    228 // shift/reduce conflicts
-%expect-rr 175 // reduce/reduce conflicts
+%expect    0
 
 // Uncomment this to get verbose error messages
 //%define parse.error verbose
@@ -2517,174 +2515,5 @@ id_opt
 
 id
     : TK_NAME { $$ = SYMBOL($1, @$); }
-    | KW_ABSTRACT { $$ = SYMBOL($1, @$); }
-    | KW_ALL { $$ = SYMBOL($1, @$); }
...
-    | KW_WAIT { $$ = SYMBOL($1, @$); }
-    | KW_WHERE { $$ = SYMBOL($1, @$); }
-    | KW_WHILE { $$ = SYMBOL($1, @$); }
-    | KW_WRITE { $$ = SYMBOL($1, @$); }
     | error { $$ = SYMBOL(LCompilers::Str(), @$); }
     ;
```
The only ambiguity is caused by the fact that keywords can be used as function/variable names, however the Fortran grammar, as designed, can be parsed unambiguously, so this ambiguity only arises if we have a bug in the grammar, or if we are using the LFortran interactive extension of the grammar (statements/expressions are allowed in global scope). We used to test this at the CI, but I didn't port this yet when we moved from gitlab to github a few years ago.

So when you are changing the grammar, just apply the above patch, and if there are no conflicts, then your change is fine. I call all conflicts induced by the above patch "nonessential conflicts". And "essential conflict" would be a conflict that is still there even after the above patch, meaning an "essential conflict" will make the grammar not LALR(1). We don't have any essential conflicts.

It's quite common when you rework the grammar that the nonessential conflict numbers change (either new one appears, or they move from shift/reduce to reduce/reduce and vice versa), there is no problem in that.
