### ISSUE TITLE
Bad loop variable

### ISSUE THREAD

**Issue by harperjf** [lfortran/lfortran#5761]
Lfortran 0.42.0 gives wrong results from this program with every option tried. The issue arose from a comment by @certik in #5739. The loop variable ```i``` has the wrong value after one of the loops; which loop it is depends on an option.
```
  integer i
  do i = 1,2
     print "(A,I0)",'In loop 1 i=',i
  end do
  print "(A,I0,A)",'After loop 1 i=',i,merge(' good',' bad ',i==3)
  do i = 1,2
     print "(A,I0)",'In loop 2 i=',i
     if (i<2) exit
  end do
  print "(A,I0,A)",'After loop 2 i=',i,merge(' good',' bad ',i==1)
  end program
```
Output with no options or ```--std=f23```
```
In loop 1 i=1
In loop 1 i=2
After loop 1 i=2 bad 
In loop 2 i=1
After loop 2 i=1 good
```
Output with ```--use-loop-variable-after-loop``` with or without ```--std=f23```
```
In loop 1 i=1
In loop 1 i=2
After loop 1 i=3 good
In loop 2 i=1
After loop 2 i=2 bad 
```
Output (correct IMHO) from 5 other compilers: gfortran, g95, ifx, ifort, AMD flang
```
In loop 1 i=1
In loop 1 i=2
After loop 1 i=3 good
In loop 2 i=1
After loop 2 i=1 good
```

**Comment by certik** [comment]
Thanks for the bug report, we need to fix that. With the option `--use-loop-variable-after-loop` it must return the same answer as gfortran.

**Comment by kmr-srbh** [comment]
I think the issue here is that the `DoLoop` exits before complete iteration, but we always increment the loop variable after the loop is over. We need to handle the increment correctly for these cases.

```fortran
! Fortran code after applying the pass: do_loops
program main
implicit none
integer(4) :: i
i = 1 - 1
do while (i + 1 <= 2)
    i = i + 1
    print *, "In loop 2 i=", i
    if (i < 2) then
        exit
    end if
end do
i = i + 1
print *, "After loop 2 i=", i
end program main
```

Pushing a fix to handle the loop break.

**Comment by saikarna913** [comment]
@kmr-srbh, Can you help me identify where the logical implementation of this `do` loop is located in our code? Is there a way to debug the code and observe its behaviour? Like if it is about an array, how to find where the implementation of the array was done in this repo, etc.. if there is any way, please help me, which will help me solve some issues faster.

**Comment by kmr-srbh** [comment]
@saikarna913 I will try to guide you through the debugging process when we encounter a bug like above. This bug has an important point to note - it is related to the use of a compiler option.

The first thing which we do when we encounter a bug, is to check the ASR. There are a few ways to have a look at it:
- `--show-asr` - Shows the initial ASR constructed from AST
- `--dump-all-passes` - Dumps files containing the ASR after each ASR pass
- `--dump-all-passes-fortran` - Dumps files containing Fortran code generated from ASR after each ASR pass

`--dump-all-passes-fortran` is convenient to see, but can sometimes be unreliable due to missing ASR node visitors. It also does not contain internal details about the code, like the variable type which the compiler got.

`--dump-all-passes` can be a bit tough to understand at first, but gets easy with time and provides much more information about the code.

The above code depends on the `--use-loop-variable-after-loop`, so we first try to find it's usage in the code and see what changes it introduces. This takes us to the `do_loop` ASR pass, which converts a `do` loop in Fortran, to a `do while` loop.

The above steps can be used to debug most bugs which we encounter. Some bugs are related to the way code is handled in the LLVM back-end, but the front-end can be responsible for the error, so it helps sometimes. In some cases though, the back-end code transformation can be solely responsible for the error.

Please let me know if you have more questions.
