### ISSUE TITLE
Document translation workflow for documentation

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#626]
We have moved to Sphinx and have multiple translations for https://docs.lfortran.org. We should now document how to translate it.

@awvwgk, I've done this before, but I forgot how to get everything setup. :) I know there are tools for Linux where it is quite comfortable to translate everything, so I'll try to document these. And later we can figure out if we want to use Weblate, especially if you like it for fortran-lang.

**Comment by awvwgk** [comment]
Can you create a webhook for weblate to finish up the integration? Instructions are available at https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

**Comment by awvwgk** [comment]
The translation is now available at https://hosted.weblate.org/projects/fortran-lang/lfortran-docs/, you need to login to add translations.

**Comment by certik** [comment]
I setup the webhook.

**Comment by certik** [comment]
@awvwgk do you know how the committed `.po` files get updated? I tried to change the English version, and rerun `python build.py`, but the `.po` files didn't change. Do I need to run some special tool to get them updated to reflect the new (changed) English text?

**Comment by awvwgk** [comment]
The build script only creates the webpage, but not update the po files, it could be done as part of the build script, though.

Updating the po-files or adding new languages is currently manually using

```
sphinx-build -b gdoc/src _build/gettext
sphinx-intl update -p _build/gettext -d doc/locale -l de,pt,es,nl,zh_CN,ja,fr
```

**Comment by awvwgk** [comment]
First PR from weblate is incoming at https://github.com/lfortran/lfortran/pull/629, you can keep it open for a while, new translations made in the web interface will be pushed to this branch until it is merged. Updates are either scheduled or done manually via the [repository maintenance](https://hosted.weblate.org/projects/fortran-lang/lfortran-docs/#repository). Once merged a new PR will be opened if further translations are made. Commits will be grouped by language and author chronologically. And that's basically all to it.

NB, since I usually don't do merge commits with git, I merged weblate PRs via *rebase and merge* so far to preserve the authorship.

**Comment by certik** [comment]
@awvwgk awesome, thanks a lot for setting everything up and the tips. I translated a few sentences myself in Weblate as well and we'll see how it goes. If I understand you correctly, we have to run the `sphinx-build -b gettext ...` and the `sphinx-intl update ...` commands from time to time and commit the results.

**Comment by certik** [comment]
Thanks @awvwgk !
