### ISSUE TITLE
Get program test cases working

### ISSUE THREAD

**Issue by richardblam** [lfortran/lfortran#995]
I propose that getting the program test cases working properly be made a higher priority. How about changing test.toml to the following for the program test cases?
```
[[test]]
filename = "program1.f90"
ast = true
asr = true
llvm = true
obj = true
cpp = true
c = true
x86 = true

[[test]]
filename = "program2.f90"
ast = true
asr = true
llvm = true
obj = true
cpp = true
c = true
x86 = true

[[test]]
filename = "program3.f90"
ast = true
asr = true
llvm = true
obj = true
cpp = true
c = true
x86 = true

[[test]]
filename = "program4.f90"
ast = true
asr = true
llvm = true
obj = true
cpp = true
c = true
x86 = true
```

**Comment by certik** [comment]
We test the program test cases using cmake in integration_tests. There is almost 300 test cases. Do you see some issues with that?

**Comment by richardblam** [comment]
Yes, the backends are in a state of disrepair and the testing is dubious. I recommend changing your software methodology so that the tests fail instead of silently pass because they are skipped.

**Comment by certik** [comment]
Thanks for the suggestion. I am not sure I understand it yet: We select which tests are supposed to work here: https://github.com/lfortran/lfortran/blob/8d8ea47f43d133a5dbeb952990498614efe15a28/integration_tests/CMakeLists.txt#L107, and the tests indeed fail if we break something, they never silently pass.

**Comment by richardblam** [comment]
No, the tests for the LFortran compiler almost all silently pass. I don't believe that you looked at my proposed changed to test.toml. The backends are almost all completely unimplemented and broken.

**Comment by certik** [comment]
Can you point me to one test that currently silently passes? That indeed would be a problem.

**Comment by richardblam** [comment]
Many tests do not contain any of the following which would test a backend:
llvm = true
obj = true
cpp = true
c = true
x86 = true

**Comment by certik** [comment]
I see. Yes, we test those backends in integration_tests, so that they run quickly. We only add a test to run_tests.py if we specifically need to test the ASR or LLVM. Otherwise we just test that the given program in integration_tests actually compiles and runs correctly, which means that the ASR and LLVM (as well as obj and x86) must be good enough to work. Adding more tests to `tests/tests.toml` slows down the execution, and thus our development speed. We still have a small team, so being able to move quickly is important.

You might be suggesting to test every combination of ASR (let's say) and ensure the LLVM backend can generate code for that. We are in the process of writing such tests, which would greatly improve our coverage. Similarly to how you tested the parser by generating random source code from the AST. If this is what you are suggesting, then I agree we should do that. I am not working on this right now, since it is not stopping us to make good progress and I am focusing on compiling Minpack and other such codes, that's a better use of my time right now, so that we can deliver quicker. But I definitely want to come back to this.

**Comment by richardblam** [comment]
I believe the confusion is that program1.f90, program2.f90, program3.f90, and program4.f90 are in the tests folder, not the integration_tests folder. These programs test other features not tested by the integration tests and the backends are not tested much for the tests folder.

**Comment by richardblam** [comment]
I am suggesting that you utilize the tests folder tests to test the backends further.

**Comment by certik** [comment]
I see. The issue is that adding more tests in the tests folder makes the test runner slower. I run tests all the time when developing, so right now at this stage it is essential that they run quickly. In a way, it seems the tests folder is more suited for the frontend tests, which end with producing the correct ASR. For backend tests we currently use the integration_tests. The program1 - 4 should be added to integration_tests if they are not there. We can rethink how to test the backends, I think a good time for that would be once LFortran reaches "beta" status (once we can compile Minpack and couple other codes).
